---
title: "us_tilapia_imports"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
# read in data
us_tilapia_imports <- read_csv(here::here("data", "us_tilapia_imports.csv")) 

# explore data
#summary(us_tilapia_imports)
names(us_tilapia_imports)
dim(us_tilapia_imports)

# reshape data- name column to create and put values from table into (values-to)
reshaped <- us_tilapia_imports %>% 
  pivot_longer(cols = '1992':'2018',
               names_to = "year",
               values_to = "tilapia_volume_kpounds" ) %>% 
  mutate(year = as.numeric(year))

# check class of year column
class(reshaped$year)

# find total us tilapia imports by year
yearly_tilapia_tot <- reshaped %>% 
  dplyr::group_by(year) %>% 
  dplyr::summarize(annual_total = sum(tilapia_volume_kpounds, na.rm = TRUE))

# create plot
yearly_tilapia_plot <- ggplot(data = yearly_tilapia_tot, aes(x = year, y = annual_total)) +
  geom_line(color = "blue")+ 
  labs(title = "USDA Economic Research Service Fishing Data",
       x = "Year",
       y = "Total tilapia imports (lbs)")

yearly_tilapia_plot

# export graph
ggsave(here::here("figs", "yearly_tilapia_plot.png"), height = 5, width = 6)

# create subset of imports
yearly_tilapia_subset <- reshaped %>% 
  filter(country %in% c("Ecuador", "Honduras", "Costa Rica", "Mexico"))

# create graph of total US tilapia imports over time for the four countries
subset_plot <- ggplot(data = yearly_tilapia_subset, 
       aes(x = year, y = tilapia_volume_kpounds)) +
  geom_point(aes(color = country))

# export graph
ggsave(here::here("figs", "subset_plot.jpg"), height = 5, width = 6)
```

